export const validationFormMessage = {
  INCOMPLETE_FORM: "Por favor, complete los campos obligatorios",
  INVALID_LENGTH_EMAIL: "El campo email debe tener entre 3 y 254 caracteres",
  INVALID_FORMAT_EMAIL: "El formato del correo es invalido. Debe tener el siguiente formato: hello@example.com",
  REQUIRED_EMAIL: "El campo email es requerido",
  INVALID_LENGTH_NAME: "El nombre debe tener entre 3 y 64 caracteres",
  INVALID_FORMAT_NAME: "El nombre no es valido. Solo puede contener letras (a-zA-Z)",
  REQUIRED_NAME: "El campo nombre es requerido.",
  REQUIRED_PASSWORD: "El campo contraseña es requerido",
  INVALID_LENGTH_PASSWORD: "La contraseña debe tener entre 6 y 128 caracteres",
  INVALID_LENGTH_PHONE_NUMBER: "El número telefónico debe tener entre 8 y 15 caracteres",
  INVALID_FORMAT_PHONE_NUMBER: "El número telefónico debe contener únicamente dígitos",
  INVALID_FORMAT_BIRTHDATE: "El formato de la fecha es invalido. Debe tener el formato: yyyy-mm-dd",
  INVALID_DATE: "La fecha es invalida",
}
